name: meetings
description: App to schedule/manage personal meetings.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.0
  provider: ^4.0.2
  rxdart: ^0.23.1
  http: ^0.12.0+1
  connectivity: ^0.4.3+2
  table_calendar: ^2.2.3
  flutter_datetime_picker: ^1.3.8
  flutter_phoenix: ^0.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  debug_mode: ^0.1.1
  flutter_launcher_icons: "^0.7.0"
  
flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/icon/icon.png